### ISSUE TITLE
Installation Documentation

### ISSUE THREAD

**Issue by jonszcz** [vonpupp/beancount_cryptocompare#1]
* beancount-cryptocompare version: Current
* Python version: 3.6.6
* Operating System: Windows 10, bash through Ubuntu

I am trying to figure out how to get this to run. I've added the path to the folder to my PYTHONPATH in both the Windows Environment Variables and to my .bashrc file as an EXPORT command, but neither of them recognize the `cryptocompareusd` module.

Below is the output that I get when running the command.

``` bash

jon@XXXXX:/mnt/c/Users/xxxxxxx$ bean-price -e USD:cryptocompareusd/ETH
Traceback (most recent call last):
  File "/home/jon/.local/lib/python3.6/site-packages/beancount/prices/find_prices.py", line 147, in import_source
    __import__(default_name)
ModuleNotFoundError: No module named 'beancount.prices.sources.cryptocompareusd'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/jon/.local/lib/python3.6/site-packages/beancount/prices/find_prices.py", line 151, in import_source
    __import__(module_name)
ModuleNotFoundError: No module named 'cryptocompareusd'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/jon/.local/bin/bean-price", line 4, in <module>
    from beancount.prices.price import main; main()
  File "/home/jon/.local/lib/python3.6/site-packages/beancount/prices/price.py", line 354, in main
    args, jobs, entries, dcontext = process_args()
  File "/home/jon/.local/lib/python3.6/site-packages/beancount/prices/price.py", line 324, in process_args
    psource_map = find_prices.parse_source_map(source_str)
  File "/home/jon/.local/lib/python3.6/site-packages/beancount/prices/find_prices.py", line 103, in parse_source_map
    for source_str in source_strs.split(','))
  File "/home/jon/.local/lib/python3.6/site-packages/beancount/prices/find_prices.py", line 103, in <genexpr>
    for source_str in source_strs.split(','))
  File "/home/jon/.local/lib/python3.6/site-packages/beancount/prices/find_prices.py", line 128, in parse_single_source
    module = import_source(short_module_name)
  File "/home/jon/.local/lib/python3.6/site-packages/beancount/prices/find_prices.py", line 155, in import_source
    module_name, exc))
ImportError: Could not find price source module "cryptocompareusd": No module named 'cryptocompareusd'
```

**Comment by vonpupp** [comment]
Hi,

I am sorry but I have never used python in windows, in fact I don't use windows. Under linux I got it working with `PYTHONPATH`, however I must warn you that this is quite alpha code so anything could happen. I have not used this in a while, so I will have to review this when I have some free time.

If you get it working before me, please feel free to send a PR so the readme gets improved.
